### ISSUE TITLE
NPM Advisory: Hijacked Environment Variables

### ISSUE THREAD

**Issue by alexander-tmsi** [MariaDB/mariadb-connector-nodejs#11]
[https://www.npmjs.com/advisories/495](https://www.npmjs.com/advisories/495)

**Comment by alexander-tmsi** [comment]
![image](https://user-images.githubusercontent.com/30027086/44935322-730a7980-ad2d-11e8-98d7-5984121aba70.png)

**Comment by knoxcard** [comment]
Think this is for the old mariadb repository, not this new one.

**Comment by rusher** [comment]
Right, that's due to previous use of npm "mariadb" package that was before this project. 
The results of discussions with npm admins is that only good solution is to have a release with version > to the old repositories. 

Next version in 2-3 weeks will solve that wrong message.

**Comment by knoxcard** [comment]
Close Ticket?
