### ISSUE TITLE
Executing multiple queries in a single string

### ISSUE THREAD

**Issue by michaelschufi** [MariaDB/mariadb-connector-nodejs#13]
Hi

I am using this package to import an sql db dump. If I am not mistaken, I have to isolate all queries including special comments like 
```mysql
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
```
because `connection.query()` only allows a single query.
Is there a way to execute multiple queries in a single string?

Regards,
Michael

**Comment by rusher** [comment]
there is one option to permit multi-queries, named 'multipleStatements' : see https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/documentation/connection-options.md

### example 
```javascript
const mariadb = require('mariadb');
mariadb.createConnection({
      host: 'mydb.com', 
      user: 'myUser',
      multipleStatements: true
    })
`
