### ISSUE TITLE
Preallocating column's length for array rows

### ISSUE THREAD

**Issue by BufoViridis** [MariaDB/mariadb-connector-nodejs#15]
https://github.com/MariaDB/mariadb-connector-nodejs/blob/71be6176923f2da49ecda9c0564a2630995560a7/lib/cmd/query.js#L428
Is it possible  to be changed to the constructor `new Array(arrayLength)`:
```js
row = new Array(columns.length);
```

**Comment by rusher** [comment]
Right !
Correction is done in [develop](https://github.com/MariaDB/mariadb-connector-nodejs/tree/develop) branch with https://github.com/MariaDB/mariadb-connector-nodejs/commit/8a5601b3f4795256576614c6fb9b85125aab4847
