### ISSUE TITLE
Piping content to Large Objects

### ISSUE THREAD

**Issue by markddrake** [MariaDB/mariadb-connector-nodejs#17]
Are there any plans to provide a mechanism for doing this... Eg uploading a large file without having to buffer it in memory. With Oracle you can do this using their CLOB object, and Postgres allows content to be streamed to stdin, which can be used with their COPY command..

**Comment by rusher** [comment]
It is already possible: Parameter just has to implement [Readable](https://nodejs.org/api/stream.html#stream_readable_streams) stream. 

Example : 
    ```

    https.get('https://someContent', readableStream => {
        //readableStream implement Readable, driver will stream data to database 
        connection.query("INSERT INTO myTable VALUE (?, ?, N)", ["other text", readableStream, 1]);
    });
```

**Comment by markddrake** [comment]
Thx, will give it a shot, new to MariaDB, I assume this will work with columns of type TEXT and BLOB ?

**Comment by rusher** [comment]
yes, that's exactly the goal

**Comment by markddrake** [comment]
Worked perfectly thank you.  Unfortunately that the lack of a JSON_TABLE like function in MariaDB totally ruined the rest of the approach..

**Comment by rusher** [comment]
What do you mean exactly ? 
JSON is handle in MariaDB. The only issue that I know concern JSON columns that have to be parsed using JSON.parse : 
like 
```
//CREATE TABLE someTable (id int, val1 JSON);
    conn
      .query("SELECT * FROM someTable")
      .then(rows => {
          const val1 = JSON.parse(rows[1].val1);
      });
```

https://jira.mariadb.org/browse/MDEV-15558 will permit to solve that in 10.4

**Comment by iangilfillan** [comment]
There are quite a few function differences between MariaDB and MySQL - JSON_TABLE() is one that exists in MySQL, but not MariaDB: https://mariadb.com/kb/en/library/function-differences-between-mariadb-103-and-mysql-80/

**Comment by rusher** [comment]
That's a different thing, created task https://jira.mariadb.org/browse/MDEV-17399 for JSON_TABLE
