### ISSUE TITLE
Issue with Load Balancer  - HAProxy, PorxySQL

### ISSUE THREAD

**Issue by mineexchange89** [MariaDB/mariadb-connector-nodejs#18]
Hello Team, 

I am trying to connect MariaDB database via load balancer (maxscale) using mariadb npm module but when we run below code we are getting error. And when try without load balancer it work perfect

Code :
```
const mariadb = require('mariadb');
const pool = mariadb.createPool({host: 'x.x.x.x', user: 'test_usr', password: '*****', port: '3307', connectionLimit: 5});

async function asyncFunction() {
  let conn;
  try {
        conn = await pool.getConnection();
        const rows = await conn.query("SELECT * from test_db.test_db");
        console.log(rows); //[ {val: 1}, meta: ... ]
//      const res = await conn.query("INSERT INTO test_db.test_db value (?, ?)", [1, "mariadb"]);
//      console.log(res); // { affectedRows: 1, insertId: 1, warningStatus: 0 }

  } catch (err) {
        throw err;
  } finally {
        if (conn) return conn.end();
  }
}

```

Error :

node mariasql_demo.js 
```
events.js:183 
throw er; // Unhandled 'error' event 
^ 
Error: Host '192.168.5.13' is not allowed to connect to this MariaDB server 
```

I am able to connect using MySQL Client. Also able to connect with mysql npm module. 

``` 
var mysql = require('mysql');

var con = mysql.createConnection({
  host: "192.168.5.19",
  user: "test_usr",
  password: "*****",
  port: "3307",
  database: "test_db"
});

con.connect(function(err) {
  if (err) throw err;
  con.query("SELECT * FROM test_db", function (err, result, fields) {
    if (err) throw err;
    console.log(result);
  });
});

```

**Comment by rusher** [comment]
> Host '192.168.5.13' is not allowed to connect to this MariaDB server 
That error seems quite clear. 

Just to confirm: when you connect using mysql npm module, you use maxscale too with the same authentications informations?

I don't think that's the case here, because the message will not correspond, but if you have using maxscale version previous to 2.1, please try disabling pipelining (setting the option "pipelining" to false).

**Comment by mineexchange89** [comment]
Yes ... For mysql npm module i am using maxscale with the same user name and password.

```
MaxScale Version : 2.2.5
node version : v8.11.3
```
Please find attached file for maxscale configuration.

[Config_Data.txt](https://github.com/MariaDB/mariadb-connector-nodejs/files/2459842/Config_Data.txt)
