### ISSUE TITLE
use plain 'connectionString' is not support?

### ISSUE THREAD

**Issue by victor0801x** [MariaDB/mariadb-connector-nodejs#25]
as title, 
mysql/mysql2 support using connection-string to createConnection or Pool
https://github.com/mysqljs/mysql/issues/907
like 
```js
mysql.createConnection('mysql://user:pass@host/db?debug=true&charset=BIG5_CHINESE_CI&timezone=-0700');
```
any plan to support this?

**Comment by rusher** [comment]
I don't think it's better than JSON options, but no reason not to provide this functionnality. 
That will be added for next release.

**Comment by victor0801x** [comment]
indeed, JSON obj. is more readable and flexible, but providing this functionnality increae compatibility with mysql/mysql2.
Thanks for your reply

**Comment by rusher** [comment]
The latest release (2.0.1) does now have this possibility.

**Comment by victor0801x** [comment]
great, but it seem not compatable to mysql ? like 'mysql://...'
`not ok error parsing connection string 'mysql://root@localhost/mysql'. format must be 'mariadb://[<user>[:<password>]@]<host>[:<port>]/[<db>[?<opt1>=<value1>[&<opt2>=<value2>]]]'`

**Comment by rusher** [comment]
Connection String works the same way, but the prefix is different (i.e. begin with 'mariadb://'). 
It's a minor annoyance since an error message will tell that, and that's better in the long run.

**Comment by victor0801x** [comment]
agree, it's better in the long run. but, perhapse we can show warning not throw error?
and, is this more maintainable? (copy from mysqljs)
```js
const urlParse = require('url').parse;

url = urlParse(connectionString, true);
const options = {
  host: url.hostname,
  port: url.port,
  database: url.pathname.substr(1)
};

if (url.auth) {
  const auth = url.auth.split(':');
  options.user = auth[0];
  options.password = auth[1];
}
if (url.query) {
  for (const key in url.query) {
    const value = url.query[key];
    try {
      // Try to parse this as a JSON expression first
      options[key] = JSON.parse(value);
    } catch (err) {
      // Otherwise assume it is a plain string
      options[key] = value;
    }
  }
}
```

**Comment by rusher** [comment]
Hmm, that might be a solution (warning, in place of error). 

Using require('url') just to identify hostname, user and password, and options with Try catch of JSON.parse seem an overkill, and unnecessary slowing this parsing (and a lot). 

... but this shows me an issue in current implementation for parameters that can accept JSON (like SSL). I need to correct that.
