### ISSUE TITLE
Connection pooling: Cannot read property 'threadId' of undefined

### ISSUE THREAD

**Issue by izzymg** [MariaDB/mariadb-connector-nodejs#26]
Occasionally when running multiple queries asynchronously I get this error. It boils down to line 431 in pool.js, handleTaskQueue()

```
    const task = taskQueue.shift();
    if (task) {
      const conn = idleConnections.shift();
      activeConnections[conn.threadId] = conn;

      resetTimeoutToNextTask();
```

The return value of idleConnections.shift() is undefined, and throwing this exception. Restarting my node application a few times, it happens about 60% of the time and only with several queries happening. My code looks like:

```
exports.get = async function (query, values) {
    let connection;
    try {
        connection = await Pool.getConnection();
        const response = await connection.query(query, values)
        connection.end();
        return response;
    } catch (err) {
        if (connection) {
            connection.end();
        return { err: 500 };
    }
```

The code that's bugging it is two calls to get in a Promise.all(); Is my use of the connection pool wrong? Thanks.

**Comment by izzymg** [comment]
As far as I know that's not the intended design, internally the pool opens one authorised instance to the DB and calling .end releases that connection back into the pool to be reused for another query. Also, what's the relevance of that to the error?

**Comment by rusher** [comment]
@izzymg Could you please indicate the version you're using.
Can you confirm it's before 2.0.1? That the exact problem has been corrected in the last release (2.0.1)

**Comment by izzymg** [comment]
@rusher Looks like it was 2.0.0 alpha, hah. Thanks.

**Comment by knoxcard** [comment]
@izzymg - close ticket?
