### ISSUE TITLE
is deps "npm" still use ?

### ISSUE THREAD

**Issue by victor0801x** [MariaDB/mariadb-connector-nodejs#29]
seems `npm` deps has some medium severity issue !?
![2018-12-10 18-47-34](https://user-images.githubusercontent.com/4534038/49729021-444a5a80-fcaf-11e8-95d0-fdc11629b200.png)
![2018-12-10 18-47-44](https://user-images.githubusercontent.com/4534038/49729030-48767800-fcaf-11e8-9070-2f3e10fccb7a.png)

but, I cannot find where this driver use `npm` lib
shoud remove this npm deps ?

**Comment by rusher** [comment]
oh, npm 6.4.1 has this severity error and npm is listed as dependency without need (
https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/package.json#L45)
 
There is no need for that, I'll remove that

**Comment by victor0801x** [comment]
`2.0.2` released
thanks @rusher
