### ISSUE TITLE
Integration with Sequelize

### ISSUE THREAD

**Issue by knoxcard** [MariaDB/mariadb-connector-nodejs#3]
This DB connector needs to be integrated with [Sequelize](https://github.com/sequelize/sequelize/), the most popular MariaDB ORM .

We are going to need...
1) typecast API (preferably for both query / execute)
2) prepared statements, it is not a must but all other dialects now support this and we are going to implement them everywhere if possible
3) supportBigNumbers / bigNumberStrings like api
@sushantdhiman

Hmm, I also see Node.js 7.6+ is required???

**Comment by rusher** [comment]
Hi @knoxcard 

typecast is implemented : [example ](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/test/integration/test-typecast.js#L21)

Binary statements (mysql2 execute) are not available for now. Those may even slow down query (PREPARE + EXECUTE + CLOSE) compare to standard text command. There is some discussion to improve that in MariaDB 10.4, but I don't see that as a must-have. That will probably be added in a very near future because there is no reason to not provide this functionality, but in most of the use case, I would recommend using standard text protocol (query)

supportBigNumbers / bigNumberStrings are implemented too. 

>Node.js 7.6+ is required???
yes, implementation use async / await for pool

**Comment by knoxcard** [comment]
@sushantdhiman

**Comment by sushantdhiman** [comment]
@rusher Sequelize use its own pool so if possible can you provide an export with just `creationConnection`, like a new file `connection` which just export `createConnection` without any pooling?

Then we can just require `mariadb/connection`, We want to support Node v6 thus can't use any code using async await

**Comment by rusher** [comment]
@sushantdhiman then you can use createConnection (https://github.com/MariaDB/mariadb-connector-nodejs#createconnectionoptions--promise)

btw, I've checked your pool implementation. I would recommend having another option like the "[minDelayValidation](https://github.com/MariaDB/mariadb-connector-nodejs#pool-options)" implemented in this driver to avoid always validating the connection.

Using this driver, 2 connection methods are available : 
* connection.isValid() → boolean : just verify that connection is valid as connector knows it
* connection.ping() → Promise: complete validation, sending a one byte packet and reading server result.

**Comment by sushantdhiman** [comment]
@rusher yeah but I can't do `require('mariadb')` on Node 6 target, it will throw an Syntax error, you have to provide an export which don't require `pool.js` at all.

**Comment by sushantdhiman** [comment]
I can however require both `connection.js` and `config/connection-options` and recreate `createConnection` but I rather not expose Sequelize to dialect internals, It would be great to have an export with just `createConnection`

**Comment by sushantdhiman** [comment]
Great, hopefully will get released soon.

**Comment by knoxcard** [comment]
Weekly Downloads - this is just a reference
---------------------------------------------------------------
https://www.npmjs.com/package/mariadb: **139**
https://www.npmjs.com/package/sequelize: **166,894**

Out of those 166,000+ downloads, something like 20% to 30% are MariaDB.  The world needs this optimized streaming code.  I can carve out on some time soon to help with the Sequelize connector, if my help is welcomed.  Thanks @rusher

**Comment by rusher** [comment]
This will be released in september. 
This is a major task.

**Comment by rusher** [comment]
PR submitted : https://github.com/sequelize/sequelize/pull/10192

**Comment by sushantdhiman** [comment]
PR has been merged to master https://github.com/sequelize/sequelize/pull/10192 Now sequelize offers dedicated MariaDB support using this connector :tada:

**Comment by knoxcard** [comment]
@rusher Nice job!

**Comment by knoxcard** [comment]
when i set dialect ':mariadb', an error is thrown.  I appear to have the latest version as well.

**Comment by rusher** [comment]
it's on the master branch, but that is not released yet

**Comment by knoxcard** [comment]
I will go ahead and close this ticket now.
