### ISSUE TITLE
Possible Roadmap Addition

### ISSUE THREAD

**Issue by knoxcard** [MariaDB/mariadb-connector-nodejs#32]
@rusher This last week I read about MySQL partitioning and MariaDB appears to offer the same feature.  This is a must for large scale applications.  Might be too early for all this, but just wanted to bring it to your attention.

https://mariadb.com/kb/en/library/partitioning-overview/

**Comment by rusher** [comment]
This is already possible actually and there is nothing to change. SPIDER has an internal proxy that will take care of redirecting to good partition, split the query into multiple server nodes ... and a lot more. 
From the connector point of view, there is nothing to change.

**Comment by knoxcard** [comment]
Great! Thanks
