### ISSUE TITLE
handling query result 

### ISSUE THREAD

**Issue by fas3r** [MariaDB/mariadb-connector-nodejs#41]
Hello, 

That's probably a dumb question but how should I handle the result `rows` of the query in the example below, meaning access it.. 

Should I do first a `rows.lenght` to check if there are data and then `rows.map(...)` to access/manipulate the data ?

Thanks by advance.

```
const mariadb = require('mariadb');
const pool = mariadb.createPool({host: 'mydb.com', user: 'myUser', connectionLimit: 5});

async function asyncFunction() {
  let conn;
  try {
	conn = await pool.getConnection();
	const rows = await conn.query("SELECT * FROM .. ");
	console.log(rows); //[ {val: 1}, meta: ... ]
        .....
  } catch (err) {
	throw err;
  } finally {
	if (conn) return conn.end();
  }
}
```

**Comment by knoxcard** [comment]
```
if(rows) {
   ...
}
```

**Comment by fas3r** [comment]
thanks :)

**Comment by knoxcard** [comment]
@fas3r - close ticket?

**Comment by fas3r** [comment]
Hello @knoxcard , 
I tried even if length is 0 it goes in the condition, strange.

Br,

**Comment by knoxcard** [comment]
I am so used to the MariaDB ORM [Sequelize](https://github.com/sequelize/sequelize), my apologies.

How about this?
if(rows.length) {
 ...
}

**Comment by knoxcard** [comment]
@rusher - your thoughts?

**Comment by knoxcard** [comment]
I contacted the author, @rusher for the most minimal correct code solution to checking if rows exist.

In the meantime, how about this?
```
if(Object.keys(rows).length) {
...
}
```

**Comment by fas3r** [comment]
Hello @knoxcard,

Thanks, it’s what I do at the moment I check the length of rows and if > 0 I do what I have to do with the data.. 

 I just realized that maybe if is not even necessary and a rows.map(row=>...) or a for(const row of row) {...} is just enough..  

If the array (rows) is empty, it should not be processed by map or for. 

 I will need to confirm later on today . Thanks

**Comment by rusher** [comment]
for a SELECT query that run without issue, results will always be an array.
If result doesn't have any rows, that means an empty array, not null.
So if using promise implementation, you can always use rows.map(...).

That's not the case if using callback implementation since only error will be set

**Comment by knoxcard** [comment]
so maybe this will work too?

```
if(Array.isArray(rows)) {
}
```

**Comment by fas3r** [comment]
Hello @rusher , 

Thanks, yes I did a test yesterday it works fine with .map() .. ( Yes I do yes async / await ... a lot, not sure if that's good or bad ;D ).

closing the ticket. Thanks
