### ISSUE TITLE
Missing type definitions for typescript

### ISSUE THREAD

**Issue by danieldaeschle** [MariaDB/mariadb-connector-nodejs#42]
Is there something incoming?

**Comment by knoxcard** [comment]
@danieldaeschle  - ? please elaborate...

**Comment by danieldaeschle** [comment]
What should i elaborate?

Do you know type definitions for typescript?
There is nothing. I just wanted to ask if someone can add them or maybe something is in planning?

**Comment by knoxcard** [comment]
@danieldaeschle - I understand now. At first I thought you were reporting an error being thrown, instead of a feature request. My apologies.

**Comment by dupkey** [comment]
I took a stab at them awhile back but they were a little more complex than what I could handle. Feel free to use as a start.

[interfaces.d.ts](https://gist.github.com/dupkey/c8c7636fe5521321aa1fbbfd56223d77)
[promise.ts](https://gist.github.com/dupkey/674199a229d6968bec6f77478039ad85)

**Comment by rusher** [comment]
Added with commit https://github.com/MariaDB/mariadb-connector-nodejs/commit/dbd2f87a2ee54bb414702eec776e117ec05fb674
