### ISSUE TITLE
Serverless Lambda Too many connections

### ISSUE THREAD

**Issue by dupkey** [MariaDB/mariadb-connector-nodejs#43]
I'm trying to use the connector in an AWS Lambda function (right now just testing with serverless-offline) but I'm receiving console warnings until it finally errors out completely. My event is scheduled to run every minute so it uses up the available connections rather quickly. From the research I've done this seems like a known issue with mysql-like connectors. None of the solutions I've found seem to work. Any help is greatly appreciated. Thanks.

```
serverless_1  | pool fail to create connection ((conn=-1, no: 1040, SQLState: HY000) Too many connections)
mariadb_1     | 2019-03-06 20:22:00 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'root' host: '172.20.0.4' (Got timeout reading communication packets)
```

```
import * as mariadb from 'mariadb';

const pool = mariadb.createPool({
  host: process.env.MARIADB_HOST,
  user: process.env.MARIADB_USER,
  password: process.env.MARIADB_PASSWORD,
});

export const handler = async () => {
  let conn;
  try {
    conn = await pool.getConnection();
    const rows = await conn.query("SELECT 1 as val");
    console.log(rows);
    await conn.end()
  } catch (err) {
    console.error(err);
  }
  ...
}
```

**Comment by knoxcard** [comment]
@rusher

**Comment by knoxcard** [comment]
Interesting....https://spotinst.com/blog/2017/11/19/best-practices-serverless-connection-pooling-database/

**Comment by dupkey** [comment]
Thanks for the link @knoxcard it seems like I'm following their best practices by keeping the connection pool outside of the my handler function.

I also tried the approach of creating my connection inside the handler but that didn't work at all. [https://www.reddit.com/r/aws/comments/824v41/too_many_connections_rdsaurora_mysql_lambdanodejs/e3x197l/](https://www.reddit.com/r/aws/comments/824v41/too_many_connections_rdsaurora_mysql_lambdanodejs/e3x197l/)

**Comment by rusher** [comment]
hi @dupkey. To confirm what knoxcard indicate:
pool must be defined only one time : pool will create by default 10 connections

So if pool is created each time handler is called, this will end badly with 'too many connections'.

Lambda functions are stateless, so there is no way to share a connection pool between functions. 
Solution is to create a new connection each time (and end it when finished).

**Comment by dupkey** [comment]
That makes sense and it seems to be working now. Thanks for your help @rusher 

```
import * as mariadb from 'mariadb';

export const handler = async () => {
  let conn = await mariadb.createConnection({host: process.env.MARIADB_HOST, user: process.env.MARIADB_USER, password: process.env.MARIADB_PASSWORD});
  try {
    let rows = await conn.query("SELECT 1 as val");
    console.log(rows);
    await conn.end();
  } catch (error) {
    console.error(error);
  }

  return {
    statusCode: 200,
    body: JSON.stringify({ message: 'dev/null.' })
  }
}
```
