### ISSUE TITLE
cannot insert blob that exceeds max_allowed_packet

### ISSUE THREAD

**Issue by kFo** [MariaDB/mariadb-connector-nodejs#47]
Got a packet bigger than [max_allowed_packet](https://mariadb.com/kb/en/library/server-system-variables/#max_allowed_packet) bytes

```
const fs = require('fs');
const mariadb = require('mariadb');
const db = mariadb.createPool({
  host: 'localhost',
  port: 3306,
  user: 'user',
  password: 'password',
  database: 'my_database'
});

let conn;
try {
    conn = await db.getConnection();
    const file = fs.createReadStream('/my/big/file.zip');
    await conn.query({ sql: 'insert into `my_big_table`(`data`) values(?)' }, [file]);
}
catch(err) {
    console.log(err); // Got a packet bigger than 'max_allowed_packet' bytes
}
finally {
    if ( conn )
        conn.end();
}
```

I need the equivalent of the C connector's [mysql_stmt_send_long_data](https://mariadb.com/kb/en/library/mysql_stmt_send_long_data/). Is there any workaround other than increasing max_allowed_packet?

**Comment by knoxcard** [comment]
Reference: https://stackoverflow.com/questions/53879973/is-there-any-way-to-set-max-allowed-packet-in-mysql-npm

**Comment by rusher** [comment]
Hi @kFo.

At some point (version 2.1.0), binary protocol will be implemented with [COM_STMT_SEND_LONG_DATA]( https://mariadb.com/kb/en/library/com_stmt_send_long_data/).

For the moment, there is actually no other solution other than increasing [@@max_allowed_packet](https://mariadb.com/kb/en/library/server-system-variables/#max_allowed_packet).

**Comment by knoxcard** [comment]
How to increasse @@max_allowed_packet

https://stackoverflow.com/questions/8062496/how-to-change-max-allowed-packet-size

**Comment by knoxcard** [comment]
Whoa, I didn't know about this trick, you can do the following...

// right after you successfully connect to MariaDB
db.query('SET GLOBAL max_allowed_packet=1073741824;')

// this important, you must drop all your existing connections and reconnect
db.disconnectAllConnections()
db.reconnectAllConnections()

// should output "1073741824"
db.query('SHOW VARIABLES WHERE variable_name = 'max_allowed_packet'')

So it appears you can get this to work without have to set it in **my.cnf**

**Comment by rusher** [comment]
Still, max_allowed_packet exist to avoid using server ressources that doesn't corresponds to expected results. Principle is that max_allowed_packet limit must be set accordingly to maximum query size. 

Even if at some point binary protocol will be used (with 10.5 that will have some new optisation that will permit this binary protocol to be faster than existing implementation), the good solution is to increase max_allowed_packet to expected command size.
