### ISSUE TITLE
Sequelize Warning: please use IANA standard timezone format ('Etc/GMT0')

### ISSUE THREAD

**Issue by knoxcard** [MariaDB/mariadb-connector-nodejs#48]
Upon loading the latest release, the following warning immediately gets thrown on app startup.

```
warning: please use IANA standard timezone format ('Etc/GMT0')
```
I'd like to prevent the warning from displaying in the console and continue as I had always been with UTC.

Do I have to do anything?

**Comment by rusher** [comment]
hi @knoxcard. 
Indeed, 2.0.4 version now rely on [IANA](https://www.iana.org/time-zones) timezone definition. 
format +/-hh:mm is still working, but there is a warning displayed to use IANA standard. 

If i'm not wrong, you use '+00:00' that correspond to 'Etc/UTC' that lots of aliases : 
* Etc/GMT-0
* Etc/GMT
* Etc/GMT+0
* Etc/GMT0
* Etc/Greenwich
* GMT

any of those and warning will disappear.

**Comment by knoxcard** [comment]
```
var sequelize = new Sequelize(connStr, {
    dialectOptions: {
        useUTC: false //for reading from database
    },
    timezone: '+08:00' //for writing to database
});
```

**Comment by knoxcard** [comment]
/lib/config/connect-options.js
```
    console.log(JSON.stringify(opts, null, 4))
    console.log('opts.timezone: ' + opts.timezone)
```

**Comment by knoxcard** [comment]
Ah I see the problem.
This logic needs to be added...

```
var timezone = opts.timezone
if(!timezone)
  timezone = opts.define.timezone
if(!timezone)
  timezone = opts.define.dialectOptions.timezone
```

**Comment by knoxcard** [comment]
Scratch everything....lol...well sort of, i think my previous post logic...there might be some good in creating something like that, but really, going forward, there should only be one way to set the timezone in Sequelize.

Here is the magical Sequelize config that gets rid of the warning message, without modifying any source at the moment.

```
  var Sequelize = require('sequelize'),
    sequelize = new Sequelize(process.env.db_name, process.env.db_user, process.env.db_pass, {
      dialect: 'mariadb',
      port: process.env.db_port,
      pool: {
        min: 1,
        max: 60,
        idle: 10000
      },
      define: {
        charset: 'utf8mb4',
        timestamps: false,
        hooks: {
          afterCreate: (model, fn) => {
            app.get('functions').dbModelFormatJsonColumns(model, fn)
          },
          afterUpdate: (model, fn) => {
            app.get('functions').dbModelFormatJsonColumns(model, fn)
          }
        }
      },
      dialectOptions: {
        collate: 'utf8mb4_general_ci',
        useUTC: true,
        timezone: process.env.db_timezone
      },
      benchmark: false,
      logging: false
    })
```

**Comment by rusher** [comment]
oh, right. for sequelize, since [this change](https://github.com/sequelize/sequelize/pull/10705/files), IANA timezone is changed to offset. 

So when using the last version of sequelize, you cannot get rid of this warning without setting Node.js default timezone to UTC (environment variable TZ),  removing `timezone` option and enable `keepDefaultTimezone`  option.

I'll create a PR in sequelize to change that behaviour.

**Comment by knoxcard** [comment]
Should this be carried over to JIRA as well?

**Comment by jesse996** [comment]
still have this warning

**Comment by knoxcard** [comment]
@jesse996 - are you using Sequelize?

**Comment by knoxcard** [comment]
@jesse996 - are you still having this issue?

**Comment by wlensinas** [comment]
> still have this warning
@jesse996 - I have the same warning, I fix it with add 'dialectOptions' to the object.

```
 dialect: 'mariadb',
  dialectOptions: {
    timezone: 'Etc/GMT-3',
  },
```
[Source](https://github.com/sequelize/sequelize/issues/10921#issuecomment-491429685)

**Comment by knoxcard** [comment]
@wlensinas - that is absolutely correct.  Thanks for just showing the minimal code example required to get the warning to disappear!  Much more precise than my answer.

**Comment by kylynf** [comment]
@jesse996  and @knoxcard 

@jesse996's answer works for me in regular queries; however in my migrations I am still getting the timezone warning. Did anyone figure out a solution to the warning while using a migration?

**Comment by kylynf** [comment]
I did try undoing and rerunning my migrations, for the record

**Comment by knoxcard** [comment]
@kylynf - are you using Sequelize for migrations? Need more info on how you are doing migrations.  I personally do not use migrations at all, but can still assist.

**Comment by abuuzayr** [comment]
thanks @wlensinas! that works for me.

**Comment by abuuzayr** [comment]
@kylynf are you using `sequelize-cli`, did `sequelize init` and therefore auto-generated `config/config.json`? 

If that's the case, try adding that `dialectOptions` key and object to your required environment in `config/config.json`. 

Therefore something like..

```
  "development": {
    "username": "username",
    "password": "password",
    "database": "database",
    "host": "host",
    "dialect": "mariadb",
    "operatorsAliases": false,
    "dialectOptions": {
        "timezone": "Etc/GMT+8"
    }
  },
```

**Comment by knoxcard** [comment]
@kylynf - thanks for posting the problem you were experiencing and thank you even more for taking the time to come back and post the solution!

**Comment by lukegalea16** [comment]
I am using mariadb and setting timezone in dialect options but created_at and updated_at fields remain as server timezone.
