### ISSUE TITLE
Cannot set Timezone on connection using SYSTEM timezone

### ISSUE THREAD

**Issue by grgrssll-dev** [MariaDB/mariadb-connector-nodejs#52]
lib version v2.0.5
Maria v10.3.13
Connection via Sequelize v5

```
{ 
  Error: (conn=55, no: 45036, SQLState: 08S01) Automatic timezone setting fails. Server timezone 'PDT' does't have a corresponding IANA timezone. Option timezone must be set according to server timezone
    at Object.module.exports.createError (/some/directory/node_modules/mariadb/lib/misc/errors.js:56:10)
    at query.then.res (/some/directory/node_modules/mariadb/lib/connection.js:730:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
     fatal: true,
     errno: 45036,
     sqlState: '08S01',
     code: 'ER_WRONG_AUTO_TIMEZONE'
}
```

When I try to connect I am getting this error, I'm not sure why because my coworker has the same settings and it is working for him. Connecting through Sequelize v5.

The error points to this file: `/node_modules/mariadb/lib/connection.js:730:20` where I see this query: `SELECT @@system_time_zone stz, @@time_zone tz` The output of which reads: 

stz | tz
------------ | -------------
PDT | SYSTEM

however the next part of the code does a lookup in moment which is expecting an IANA timezone string like 'America/Los_Angeles' but it is getting fed the argument 'PDT' so it returns null...

As seen in the moment docs here:
https://momentjs.com/timezone/docs/#/zone-object/abbr/ 

```
const serverTimezone = res[0].tz === 'SYSTEM' ? res[0].stz : res[0].tz;
const serverZone = moment.tz.zone(serverTimezone); 
// serverTimezone is 'PDT' here not 'America/Los_Angeles' and serverZone is null as a result...
```
I've tried setting my timezone in mariadb to the IANA America/Los_Angeles but it says it's invalid... 

How can I get this working?

**Comment by grgrssll-dev** [comment]
It seems to work if I use 'US/Pacific' instead of 'America/Los_Angeles' in the options.timezone

**Comment by knoxcard** [comment]
I know this might sound stupid, but have you tried...

yarn add https://github.com/MariaDB/mariadb-connector-nodejs.git
or
npm install https://github.com/MariaDB/mariadb-connector-nodejs.git

**Comment by rusher** [comment]
Can you indicate sequelize and moment-timezone versions in package-lock.json ? 
I fail to understand how 'US/Pacific' instead of 'America/Los_Angeles' would change anything with the latest version.

**Comment by grgrssll-dev** [comment]
The mariadb-connector-nodejs does not help...

sequelize: 5.8.6
moment-timezone: 0.5.25

The sequelize constructor options for dialectOptions are

```
// Doesn't work
dialectOptions: {
    timezone: 'America/Los_Angeles',
},
```
ER_WRONG_AUTO_TIMEZONE

```
// Does work
dialectOptions: {
    timezone: 'US/Pacific',
},
```

**Comment by knoxcard** [comment]
Everything good? Close issue?

**Comment by rusher** [comment]
ok, found the issue. Using timezone exactly corresponding to client current timezone might cause automatic retrieval of server timezone. 
This is corrected with https://github.com/MariaDB/mariadb-connector-nodejs/commit/9fc5d2364b6f5f6158a17b692b01ee4501c51bae that will be in next release

**Comment by grgrssll-dev** [comment]
Fix verified working for me. Thanks
