### ISSUE TITLE
Remove Timezone Output from Console

### ISSUE THREAD

**Issue by knoxcard** [MariaDB/mariadb-connector-nodejs#53]
Can the timezone output be removed on app startup?

IANA format: 2019-05-15T22:45:30-07:00

**Comment by rusher** [comment]
hi @knoxcard , not sure to follow what you mean. Can you elaborate?

**Comment by knoxcard** [comment]
Forgot to include the word "Can".  Can the timezone output be removed on app startup?

There is a console.log('IANA Format...') somewhere in the code, correct?

**Comment by knoxcard** [comment]
I am an idiot, it was on my side, of course! So no problem here whatsoever, closing issue.
