### ISSUE TITLE
FieldInfo.type is string and not Types

### ISSUE THREAD

**Issue by leon** [MariaDB/mariadb-connector-nodejs#54]
using Typescript.

I want to do some type casting when returning data.
So I use the `typeCast` function that is available on the `createPool` options

My problem is that the parameter `FieldInfo.type` is typed as a mariadb.Types which is a enum with values such as `TINY = 0x01, // aka TINYINT, 1 byte`

But the FieldInfo.type is of type `string`. Which causes typescript to complain.

Example

```ts
const pool = createPool({
  host: 'localhost',
  user: 'root',
  password: '',
  database: 'testdb',
  connectionLimit: 5,
  typeCast: (field: FieldInfo, useDefaultTypeCasting) => {
    if (field.type === Types.BIT || field.type === Types.TINY) {
      // we never get here because Types.BIT is a number and field.type is a string 'BIT'
      return field.int() === 1;
    }
    return useDefaultTypeCasting();
  }
});
```

## How to fix.
in typescript  for `FieldInfo.type` introduce new enum that is string based.

**Comment by rusher** [comment]
( https://jira.mariadb.org/browse/CONJS-74 )
corrected in https://github.com/MariaDB/mariadb-connector-nodejs/commit/4b7bbf51c30bacbf3321b0eb045ae50cec9beaa0

Will be in next release 2.0.6
