### ISSUE TITLE
Improved Pooling

### ISSUE THREAD

**Issue by knoxcard** [MariaDB/mariadb-connector-nodejs#55]
Read that knex.js and supposedly other DB drivers are switching over to tarn.js for their resource pooling.
https://www.npmjs.com/package/tarn _(Notice the surge in weekly downloads)_

Could this potentially be more beneficial for pooling?

**Comment by rusher** [comment]
thanks for the info. Need to benchmark that

**Comment by knoxcard** [comment]
Closing...moving this to Jira.
