### ISSUE TITLE
Placeholder not working "?" 

### ISSUE THREAD

**Issue by rizwanharun** [MariaDB/mariadb-connector-nodejs#58]
I am using MariaDB 10.3 with my reactjs with express.   It is continuously giving syntax error near placeholder "?". Please help.

**Comment by knoxcard** [comment]
Not enough info.

Are you seeing this error on the frontend console window (Client Side - Browser) or in your Linux or Windows bash console (Server Side)?

**Comment by rusher** [comment]
Could you send an example of those errors ?

**Comment by rusher** [comment]
closing since no answer. Feel free to create a new issue if this is not the case link to this one!
