### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by knoxcard** [MariaDB/mariadb-connector-nodejs#59]
https://travis-ci.org/MariaDB/mariadb-connector-nodejs/jobs/542708802

**Comment by rusher** [comment]
correction done with https://github.com/MariaDB/mariadb-connector-nodejs/commit/3eeba5ee1c4e9d7549aa857316db679c6af159a6 .
This is not related to connector, but benchmark run different things, one is benchmarking pooling with promise using [promise-mysql](https://www.npmjs.com/package/promise-mysql).
Latest release (4.0.0) change createPool function behaviour, returning a promise in place of a pool object.
