### ISSUE TITLE
feature: release connection to pool keep connected

### ISSUE THREAD

**Issue by victor0801x** [MariaDB/mariadb-connector-nodejs#6]
currently `conn.end() && conn.release()` are release/remove from pool and disconnect to db?
but, `conn.release()` should only release connection to pool but keep connected to db?

**Comment by rusher** [comment]
`conn.release()` and `conn.end()` does the same thing in the pool: give back connection to pool (release is only an alias for compatibility). 

I don't see any reason for using a pool and wanting to really end the connection (please correct me if not !). The connections will be removed only when having connectivity error or by ending the pool.

**Comment by victor0801x** [comment]
`I don't see any reason for using a pool and wanting to really end the connection`
you are right. my ori concern is `conn.end()` release connection to pool and disconnect from database. Thanks for clarify
