### ISSUE TITLE
missing poolCluster 'remove' event

### ISSUE THREAD

**Issue by mafischer** [MariaDB/mariadb-connector-nodejs#60]
https://github.com/mysqljs/mysql#poolcluster

as shown in the mysql poolCluster documentation, the poolCluster emits a remove event when a node is removed.

```
// Target Group : SLAVE1-2, Selector : order
// If can't connect to SLAVE1, return SLAVE2. (remove SLAVE1 in the cluster)
poolCluster.on('remove', function (nodeId) {
  console.log('REMOVED NODE : ' + nodeId); // nodeId = SLAVE1
});
```
mariadb does not support this:
```
poolCluster.on('remove', function (nodeId) {
TypeError: poolCluster.on is not a function
```

**Comment by rusher** [comment]
Thanks for pointing that out !
done with commit https://github.com/MariaDB/mariadb-connector-nodejs/commit/95f6068946c283c78bf50f753b252049043d0dc5 . 

This will be in the next version (2.0.6)
