### ISSUE TITLE
Collation and charset

### ISSUE THREAD

**Issue by ccinelli** [MariaDB/mariadb-connector-nodejs#62]
This code here is a little weird: 
https://github.com/MariaDB/mariadb-connector-nodejs/blob/3eeba5ee1c4e9d7549aa857316db679c6af159a6/lib/config/connection-options.js#L28-L35 and it seems to mix up collation and charset.

Using `charset: 'utf8mb4'` throws and error. Adding `collation: 'UTF8MB4_GENERAL_CI'` also throw an error. 

In order to work you need to use `charset: 'UTF8MB4_GENERAL_CI'`

Finally it looks like that if you pass `charsetNumber: 12345678` you will get a `Collations.fromIndex(224); //UTF8MB4_UNICODE_CI`

In my humble opinion `charset: 'utf8mb4' should work and use `collation: 'UTF8MB4_GENERAL_CI'` as default.  Also collations should be specified with `collation:`, no `charset`.

**Comment by knoxcard** [comment]
Funny, my Sequelize connection is set to exactly what you've mentioned...

```
  var Sequelize = require('sequelize'),
    sequelize = new Sequelize(process.env.db_name, process.env.db_user, process.env.db_pass, {
      dialect: 'mariadb',
      port: process.env.db_port,
      pool: {
        min: 1,
        max: 60,
        idle: 10000
      },
      define: {
        charset: 'utf8mb4',
        timestamps: false,
        hooks: {
          afterCreate: (model, fn) => {
            app.get('functions').dbModelFormatJsonColumns(model, fn)
          },
          afterUpdate: (model, fn) => {
            app.get('functions').dbModelFormatJsonColumns(model, fn)
          }
        }
      },
      dialectOptions: {
        collate: 'utf8mb4_general_ci',
        useUTC: true,
        timezone: process.env.db_timezone
      },
      benchmark: false,
      logging: false
    })
```

**Comment by ccinelli** [comment]
Your `dialectOptions` has *only*: 
```
        collate: 'utf8mb4_general_ci',
```

It does not work for me with *both*: 
```
charset: 'utf8mb4',
 collate: 'utf8mb4_general_ci'
```

**Comment by knoxcard** [comment]
You are using Sequelize? 
So do I have it setup incorrectly?
Do you have it setup incorrectly?

**Comment by knoxcard** [comment]
I have updated my code to this...I think you're correct.

```
  var Sequelize = require('sequelize'),
    sequelize = new Sequelize(process.env.db_name, process.env.db_user, process.env.db_pass, {
      dialect: 'mariadb',
      dialectOptions: {
        timezone: process.env.db_timezone
      },
      port: process.env.db_port,
      pool: {
        min: 0,
        max: 2,
        idle: 10000
      },
      define: {
        charset: 'utf8mb4',
        collate: 'utf8mb4_general_ci',
        timestamps: false,
        hooks: {
          afterCreate: (model, fn) => {
            formatJsonColumns(model)
          },
          afterUpdate: (model, fn) => {
            formatJsonColumns(model)
          }
        }
      },
      benchmark: false,
      logging: false
    })
```

**Comment by rusher** [comment]
Alright, there is really an issue there, because actual implementation accepts only collation name (like 'UTF8MB4_GENERAL_CI'). 
To be compatible with other drivers, option charset must be either a ... charset (ex: 'utf8mb4') or a collation name (ex: 'utf8mb4_esperanto_ci').

**Comment by knoxcard** [comment]
@rusher - you are absolutely right,  I don't know what changed, but before if I did not have both charset and collate defined, the MariaDB IANA timezone error would appear in the console.

It now works without defining either value, as shown below:
```
  var Sequelize = require('sequelize'),
    sequelize = new Sequelize(process.env.db_name, process.env.db_user, process.env.db_pass, {
      dialect: 'mariadb',
      dialectOptions: {
        timezone: process.env.db_timezone
      },
      port: process.env.db_port,
      pool: {
        min: 0,
        max: 2,
        idle: 10000
      },
      define: {
        timestamps: false
      },
      benchmark: false,
      logging: false
    })
```

**Comment by knoxcard** [comment]
@ccinelli - close issue?

**Comment by rusher** [comment]
done with commit: https://github.com/MariaDB/mariadb-connector-nodejs/commit/5eb384728a7d5fe2b50a445bdb3ad39d840bd841
So this will be in next 2.1.0 version

**Comment by ccinelli** [comment]
Are you sure it will be backward compatible? Otherwise it should  be in 3.0.0 assuming you use semver

**Comment by ccinelli** [comment]
I am not sure if this change is good.

Let me add some context: 

I had the usual problem of trying to store emojis in a table that was use `latin1` as charset. 

So I was trying to set a default in  the `sequelize` so tables use the "real" UTF8 (see https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434) as default.

In SQL you usually use:
```
CREATE TABLE IF NOT EXISTS table_name (
...
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
```

My understanding is that a `collation` adds specificity to a `charset`. 

So my first attempt was to specify both: 
```
 charset: 'utf8mb4',
 collation: 'UTF8MB4_GENERAL_CI' 
```
And I had the error. Then I looked at the code and realized that in order to make it work I had to use:
```
  charset: 'UTF8MB4_GENERAL_CI'
```

That seemed wrong since that is a collation and I reported this bug.

However I dug around and I found that other databases (if they have support them) have a different way to specify collations. So it came back to make sure it follow the npm `mysql` conventions. 

From: https://www.npmjs.com/package/mysql#connection-options
> charset: The charset for the connection. This is called "collation" in the SQL-level of MySQL (like utf8_general_ci). If a SQL-level charset is specified (like utf8mb4) then the default collation for that charset is used. (Default: 'UTF8_GENERAL_CI')

This seems a little imprecise but it makes sense. 

Does the code after this change behave in this way? It is not completely clear from the diff but from the new tests it seems that `charset` was replaced with `collation`.

**Comment by rusher** [comment]
@ccinelli here is the new implementation:
`charset` now permit to indicate charset. the connector will use default collation associate to charset. For example `charset: 'cp850'` connector will use collation 'CP850_GENERAL_CI'.
`collation` permit to indicate collation, so 'CP850_GENERAL_CI' for example.

For compatibility, it's still possible to indicate a collation `charset: 'CP850_GENERAL_CI'`, but a warning will be logged, that's why 2.1.0 is ok.

So this is compatible with other drivers. 

I'm still hesitant about multiplying options, but `charset: 'CP850_GENERAL_CI'` hurt my eyes so much i think it's better this way.

I see that this need to be better documented, I'll see to that now.
