### ISSUE TITLE
promise friendly implementation for connection.queryStream()

### ISSUE THREAD

**Issue by goshoo** [MariaDB/mariadb-connector-nodejs#66]
Hi,

I read the driver's documentation and I think that the driver is awesome.

This is a feature request - can you make connection.queryStream() promise/await friendly. The event method can easily be promisified but I think that users will be happy if they have this feature implemented.

For example Node.js driver for MongoDB has cursor what works in this way

```is
while (await cursor.hasNext()){
 let doc = await cursor.next();
}

**Comment by victor0801x** [comment]
if your node >= 10.x I prefer use this for-await-of loop
```js
	for await (const row of connection.queryStream(cmd)) {
		console.log(row);
	}
	connection.end();
```

**Comment by rusher** [comment]
I tend to agree with @victor0801x using standard [es2018 asynchronous iteration](https://exploringjs.com/es2018-es2019/ch_asynchronous-iteration.html) seem more appropriate, even if requiring node.js 10+.

Implementation is for the moment not as performant compared to event 

I mean : 
```js
	for await (const row of connection.queryStream(cmd)) {
		console.log(row);
	}
	connection.end();
```
is less performant compared to 
```js
	connection.queryStream(cmd)
		.on('data', row => {
			console.log(row);
		 })
		.on('end', () => {
			connection.end();
		});
```
but is more readable

**Comment by goshoo** [comment]
Thank you, @rusher
