### ISSUE TITLE
Save JSON as formatted

### ISSUE THREAD

**Issue by knoxcard** [MariaDB/mariadb-connector-nodejs#68]
Look what I posted here: https://github.com/sequelize/sequelize/issues/10913

Implemented this solution already on my site and it has been wonderful, this should be default behavior.  When one views there JSON column data, the data is now "readable".Who wouldn't want their data to be confusing?

When saving JSON type fields. typeNames[245] = 'JSON';  
Save the string as formatted...
```JSON.stringify(json_val, null, 4)``` instead of ``` json_val```

This alteration would have no affect on performance as well.

**Comment by rusher** [comment]
hmm, actually, JSON object are changed to text here : https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/lib/cmd/common-text-cmd.js#L152
using basic "JSON.stringify(value)". 

>This alteration would have no affect on performance as well.

Alteration would mean using more bytes to store JSON in database, that cannot be a solution. 


In a near future with MariaDB 10.5 (10.5 will permit lots of data type standard, or user-defined data type, part of that is https://jira.mariadb.org/browse/MDEV-17832) connector will be able to distinguish JSON or String (additional metadata will be sent to connector). There will be a solution to just return directly JSON object in place of a String object. 

Until then, solution are to use JSON function [JSON_DETAILED ](https://mariadb.com/kb/en/library/json_detailed/) to sql query
or using sequelize , there is different solution, without additional query, with hook, before, or in the model definition, with something like : 
```
Employee.init({
  title: {
    type: Sequelize.STRING,
    allowNull: false,
    get() {
      return JSON.parse(this.getDataValue('title'));
    },
    set(val) {
      this.setDataValue('title', JSON.stringify(val, null, 4);
    }
  }
}, { sequelize, modelName: 'employee' });

```
