### ISSUE TITLE
Insert values from object, using 'INSERT INTO table SET ?' ... ?

### ISSUE THREAD

**Issue by mjcampagna** [MariaDB/mariadb-connector-nodejs#7]
Given something like this using MySQL ...

```js
let movieInfo = {
	id: 123,
	title: 'Hit Movie'
};

pool.getConnection()
.then(conn => {

	// This works in MySQL
	conn.query('INSERT INTO movies SET ?', movieInfo, (err, res) => ...
```

... trying to do the equivalent thing using MariaDB. Meaning, the object Keys should be used as column names, and values as the values to be inserted. Is this possible, or am I missing something?

**Comment by rusher** [comment]
hmm, I didn't see that they have this possibility. replacing a '?' by a combination of values doesn't respect the usual prepared statement format. It seems an open door to issues/incomprehension.

after searching mysql implementation, i've found this issue : https://github.com/mysqljs/mysql/issues/731.

Some queries like : 
`conn.query('update someTable set ? where id=?', [ {t1: 1, t2: 2}, 1])`
would be better written in
`conn.query('update someTable set t1=?, t2=? where id=?', [ 1, 2, 1])`

Using object directly can help writing less code, but in this case, i kind of agree that this non-traditional way can lead to errors, even lead to injection if used the bad way. 

I'll create an option to permit that kind of query to permit compatibility, but disabled by default

**Comment by mjcampagna** [comment]
Sounds good. Thanks!

**Comment by rusher** [comment]
done with 852ca61 in develop branch. It will be release in next version
