### ISSUE TITLE
Getting error while using pool selector type "Order" in getConnection and fails connection in the first selection.

### ISSUE THREAD

**Issue by kkx** [MariaDB/mariadb-connector-nodejs#70]
In the second iteration when the selector is called, the retry parameter is not introduced. see [here](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/lib/pool-cluster.js#L248)
, this will cause the orderedSelector to return undefined and therefore [this line](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/lib/pool-cluster.js#L244) will throw an error

**Comment by knoxcard** [comment]
@rusher

**Comment by rusher** [comment]
right, [PR ](https://github.com/MariaDB/mariadb-connector-nodejs/pull/71) submitted by @kkx merged

**Comment by knoxcard** [comment]
Just submitted a basic PR to bump dependencies a new release version so everyone gets the latest repo.
https://github.com/MariaDB/mariadb-connector-nodejs/pull/73
