### ISSUE TITLE
what is "warning: please use option 'collation' in replacement of 'charset'" all about?

### ISSUE THREAD

**Issue by MetaiR** [MariaDB/mariadb-connector-nodejs#77]
hi,
I am getting this warning:
```
warning: please use option 'collation' in replacement of 'charset' when using a collation name ('utf8mb4_persian_ci')
(collation looks like 'UTF8MB4_UNICODE_CI', charset like 'utf8').
```
I checked the documentation and other issues but I didn't find the answer
so what is all about?

**Comment by knoxcard** [comment]
Replace `charset: utf8mb4_persian_ci` with `collation: utf8mb4_persian_ci` in your connection code.

**Comment by knoxcard** [comment]
@MetaiR - any luck?

**Comment by rusher** [comment]
[Here](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/documentation/connection-options.md#other-options) is the documentation about collation / charset. 
Any question/ feedback to improve documentation always greatly appreciated :)

**Comment by knoxcard** [comment]
@MetaiR - first thing I would try is the defaults, getting rid of both `charset` and `collation`.  Then try `collation: utf8mb4_persian_ci`.  Please let us know the results, thanks!

**Comment by MetaiR** [comment]
> [Here](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/documentation/connection-options.md#other-options) is the documentation about collation / charset.
> Any question/ feedback to improve documentation always greatly appreciated :)

Hi again,
I am using `PoolConnection` with `createPool`  function and it is not accepting `collation` as an option

**Comment by knoxcard** [comment]
Try this...

```
  const mariadb = require('mariadb'),
    pool = mariadb.createPool({
      host: process.env.db_host,
      user: process.env.user,
      password: process.env.pass,
      connectionLimit: 5,
      charset: 'utf8'
    })
```

**Comment by rusher** [comment]
TypeScript definition was missing the `collation` option. 

Option has been added by https://github.com/MariaDB/mariadb-connector-nodejs/commit/d729a65db23e12fe96cf48817e1aa48a265c2926 4 days ago.

Release will be done in a few days.

**Comment by MetaiR** [comment]
@rusher tnx man, u became my new hero
