### ISSUE TITLE
Known critical severity security vulnerability detected in mariadb

### ISSUE THREAD

**Issue by mjcampagna** [MariaDB/mariadb-connector-nodejs#8]
I received this notice from Github:

```sh
Known critical severity security vulnerability detected in mariadb <= 1.0.2 defined in package-lock.json.
```

**Comment by knoxcard** [comment]
https://www.cvedetails.com/vulnerability-list/vendor_id-12010/Mariadb.html

**Comment by rusher** [comment]
"mariadb" package name was previously used for other projects totally different from MariaDB, and blocked by npm. Package name was reserved by npm to avoid any malicious use.
1.0.2 correspond to one of those npm blocked release.

Ffor now, i'm in contact with npm support to know if those can totally be removed.

**Comment by knoxcard** [comment]
close ticket?

**Comment by rusher** [comment]
closing ticket, but this will be followed [here](https://jira.mariadb.org/browse/CONJS-45)
