### ISSUE TITLE
escape and escapeId are missing in the typings

### ISSUE THREAD

**Issue by samihult** [MariaDB/mariadb-connector-nodejs#82]
Methods `escape` and `escapeId` are missing in the TypeScript type definitions:

`Property 'escapeId' does not exist on type 'PoolConnection'`

The workaround is to pass the connection/pool as `any`, but that's suboptimal.

**Comment by rusher** [comment]
alright. 
correct with commit https://github.com/MariaDB/mariadb-connector-nodejs/commit/c600c6b2fbb3f01178f5a9f03d4bd4086e547509 
It will be released this week.
