### ISSUE TITLE
Best practices for dynamic database name

### ISSUE THREAD

**Issue by mhf-ir** [MariaDB/mariadb-connector-nodejs#83]
Connection pools is usless consider about 10k dynamic subdomain bloging:

Consider simple blogging system:

```
http://user1.blog.tld
```

**user1** is dynamic database name.

```js
const mariadb = require('mariadb');
const express = require('express')
const app = express()
const port = 3000

(async () => {
  app.use(async (req, res, next) => {
    const [, dbname] = req.hostname.match(/^([a-z][a-z0-9\-]+)\.blog.tld/i);
    if (!dbname) {
       res.status(400).send('Bad Request');
    } else { 
       // so we need create dynamic connection
       // what must we do for best practices ?
    }
  });

  app.listen(port, () => console.log(`Example app listening on port ${port}!`))
})();
```

**Comment by rusher** [comment]
Using a pool is still a good idea : To give an approximation, on a local environment, creating a connection takes 2ms while a query takes 0.05ms.
changing database is a query (`use <myDb>`); 

So, you'll need to configure a pool like : 

```js
const pool = mariadb.createPool({user: 'myUser', ...});

...
   } else { 
    let conn;
    try {
      conn = await pool.getConnection();
      // escape dbname to ensure not having injection 
      await conn.query('USE ' + conn.escape(dbname));
      // use connection
      // ...
    } catch (err) {
      console.log(err);
    } finally {
      //always release connection to pool
      if (conn) conn.release();
    }

   }
```

By default, when the connection is released to pool, pool ensures connection good state (reset transaction isolation level, reset session variables, delete user variables, remove temporary tables, ...) If you don't use some commands that might induce state like this, you can set pool option `resetAfterUse` to false, then the connector will only rollback any open transaction, avoiding to execute a query on release.
