### ISSUE TITLE
TypeError: Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by thanos101** [MariaDB/mariadb-connector-nodejs#85]
Hello,

I'm getting the following errors after refreshing the same page a couple of times in quick sessions. 
My default setting using MySQL Database is CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

Does anyone know how I could fix this?

```console
/Users/Documents/server/node_modules/mariadb/lib/cmd/common-text-cmd.js:343
        if (column.collation.index === 63) {
                             ^
TypeError: Cannot read property 'index' of undefined
    at Query.readRowData 
```

**Comment by rusher** [comment]
Searching what could cause this error, the only possibility I see for now would be having data with unknown collation. Recent MySQL collations were not present. They will be with next release (https://github.com/MariaDB/mariadb-connector-nodejs/commit/70407d870000fd307b6d1eef1c44f3adc8a3c941)
Could you confirm that you may have some tables with this kind of collation? 

You seems to describe error is sporadic, so this might not be due to that, because this would be reproducible every time if that was the case.   

Could you help with some other informations like
* possible collation of queried tables. 
* exact server version
* connection option (collation ? charset ? )
* using a pool or basic connection ?

**Comment by rusher** [comment]
other question : 
- is server configured with `init_connect` that might change charset after connection

**Comment by thanos101** [comment]
It seems very strange that after 10 refresh the error appears. See below for those info...

- possible collation of queried tables. => collation of tables and database are the same.
- exact server version => express on node's 12.13 LTS
- connection option (collation ? charset ? ) => left as default, then try setting it to same as the database
- using a pool or basic connection ? => pool connection
- is server configured with init_connect => not sure how I could find this out, but I have tested on my Mac running node and Debian buster 10.1

**Comment by thanos101** [comment]
I tried switching back to mysql2 and it works. Their default config is: 'UTF8_GENERAL_CI'. Having set this in MariaDB config connection still doesn't seem to fix it.

**Comment by thanos101** [comment]
I can see that you have this added in your next commit. I think this will solve it as that's the default on MySQL database.

- charsets[255] = new Collation(255, 'UTF8MB4_0900_AI_CI', 'utf8', 4);

**Comment by rusher** [comment]
I've created a [MySQL bug report](https://bugs.mysql.com/bug.php?id=97633). 

Default pool configuration is `resetAfterUse: true`. That means when the connection is released to pool, pool ensures connection good state (reset transaction isolation level, reset session variables, delete user variables, remove temporary tables, ...). Problem with MySQL is that this revert connection charset to default server charset, not initial charset of connection.

The default server collation UTF8MB4_0900_AI_CI wasn't known, resulting in this error. So https://github.com/MariaDB/mariadb-connector-nodejs/commit/70407d870000fd307b6d1eef1c44f3adc8a3c941 will solve issue. This is now released with 2.1.3 just published.

If you don't use some commands that might induce state change like this, you can set pool option resetAfterUse to false, then the connector will only rollback any open transaction, avoiding to execute a query on release.

**Comment by thanos101** [comment]
Thank you Diego, the latest release has fixed this issue.

I really like your connector so keep up the good work.

**Comment by sF5YRs** [comment]
i get this problem these days (after pool all dead and the app dead), and , 
really , my mariadb connector is still 2.0.5 (which i install it last year , and now is 2.3.1)
i didn't update the connector because it is net inside.
then, i set resetAfterUse to false and it works well now.
