### ISSUE TITLE
incorrectly retrieve unicode content

### ISSUE THREAD

**Issue by garan82** [MariaDB/mariadb-connector-nodejs#87]
I'm using mariadb connector nodejs `2.1.2`, it happens with `2.1.3` as well, I haven't tested other versions.
mariadb: `1:10.3.7+maria~jessie`

Following is the sample code. `name` is a column in table `users`, it can include Unicode characters. `connectionLimit` is set to some number N (e.g., 5 or 10 for example).

I notice that for the first N queries, I get the result back with correct Unicode content. From N+1 query and so on, the Unicode content is not returned correctly, they were replaced with `?`. Did I set up the DB or connector incorrectly?

``` 
const mariadb = require('mariadb');

const pool = mariadb.createPool({
  host: <removed>, 
  port: <removed>,
  user: <removed>, 
  password: <removed>,
  database: <removed>,
  connectionLimit: <some-number-N>
})

async function getUserName(userId, callback) {
  let con = null
  try {
    con = await pool.getConnection()
    const results = await con.query("select name from users where id=?", [1])
    if (results != null && Array.isArray(results) && results.length === 1) {
      callback(results[0])
    } else {
      callback(null)
    }
  } catch (err) {
    callback(null)
  } finally {
    if (con) {
      con.release()
    }
  }
}
```

**Comment by rusher** [comment]
Default pool configuration use [resetAfterUse](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#pool-options): true. That means when the connection is released to pool, pool ensures connection good state (reset transaction isolation level, reset session variables, delete user variables, remove temporary tables, ...). 

The problem with MariaDB before 10.3.13 (see [MDEV-18281](https://jira.mariadb.org/browse/MDEV-18281)) is that this reset reverts connection charset to default server charset, not initial charset of connection.

So either:
* configure server default charset to utf8mb4
* update server
* or easier to do : If you don't use some commands that might induce state change, set option resetAfterUse to false
like : 
```js
const pool = mariadb.createPool({
  host: <removed>, 
  port: <removed>,
  user: <removed>, 
  password: <removed>,
  database: <removed>,
  connectionLimit: <some-number-N>`,
  resetAfterUse: false
})
```
The connector will then only rollback any open transaction if any ( and avoiding to execute a query on release if none).

**Comment by garan82** [comment]
Thanks a lot. Adding `resetAfterUse: false` works for me.

**Comment by rusher** [comment]
Just for information, in next version (2.1.3), connector won't be using reset command on server that doesn't have reset correction (commit https://github.com/MariaDB/mariadb-connector-nodejs/commit/af6befa3ef1f95cc3c4d48c89b1d6c8adf33c609 )

**Comment by garan82** [comment]
Thank you for the head up.
